### ISSUE TITLE
ticketLink - wrong link for internal pages

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#83]
Hi,
I'm sorry. It's me again. I'm testing your great extension and found another issue in the actual version with TYPO3 9.5.3. 
I try to add the ticketLink in 'properties.html'.
```
  <f:if condition="{day.event.ticketLink}">
    <f:render arguments="{event: day.event}" section="ticketLink"/>
  </f:if>
```
The first strange phenomenon: I see the label and the link only when I have inserted
`<f:debug>{day.event}</f:debug>`
in the template. I really don't know why. Maybe the arguments are wrong?

The second problem: When I choose an internal link for the ticketLink I get the following wrong URL in frontend:

```
<a title="Zum Ticketverkauf" target="_blank" href="t3://page?uid=150">
Pforte <span aria-hidden="true" class="icon-arrowright"></span></a>
```
Regards
Hobokens

**Comment by Hobokens** [comment]
Okay, I've seen now that you use
`<f:link.external>`
for the ticket and the organizer. It would be helpful to have all kinds of links here. 

By the way I still have the problem than I can see all variables when I debug them i.g.

`<f:debug>{day.event.organizer}</f:debug>`

![debug_organizer](https://user-images.githubusercontent.com/6764582/51750400-45461880-20b2-11e9-8336-521053c023e5.png)

But when I debug i.g.
`{day.event.organizer.organizer}`
The result is NULL
When I add 
`{day.event.organizer}
somewhere in the template I can debug 
`{day.event.organizer.organizer}`
successfully.



`

**Comment by froemken** [comment]
Hello @Hobokens 

I have just pushed a new version to master.
I have switches to f:link.typolink instead of f:link.external.
Further I have added TicketLink in general to template.

Stefan

**Comment by Hobokens** [comment]
Thanks for the update. I would switch to f:link.typolink instead of f:link.external for the organizer too. An example is a university where you have a lot of internal organizers.

Unfortunately I still have the problem with organizer and ticketLink.

I can 
`<f:debug>{day.event.organizer}</f:debug>`

and see all the variables.

When I debug e.g.

`<f:debug>{day.event.organizer.organizer}</f:debug>`

The result is NULL. The same problem exists with ticketLink.
I have no idea what might be causing this.

Regards
Hobokens

**Comment by Schweriner** [comment]
@Hobokens I think your issue (and mine as well) is related to a bug of the fluid template engine: https://forge.typo3.org/issues/87651
